import type { Metadata } from "next";
import Image from "next/image";
import { CalendarDays, ExternalLink, Play, Star, Tv2 } from "lucide-react";
import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { ListEditor } from "@/components/list-editor";
import { FavoriteButton } from "@/components/favorite-button";
import { MediaGrid } from "@/components/media-grid";
import { SectionHeading } from "@/components/section-heading";
import { getMedia } from "@/services/anilist";
import { translateToSpanish } from "@/services/translation";
import { mediaTitle } from "@/types/media";
import { stripHtml } from "@/lib/utils";

interface Props { params: { id: string } }
async function mediaDescription(description: string | null | undefined) { return translateToSpanish(stripHtml(description)); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { try { const media = await getMedia(Number(params.id)); const description = await mediaDescription(media.description); return { title: mediaTitle(media), description: description.text.slice(0, 155) }; } catch { return { title: "Detalle" }; } }
export default async function MediaDetail({ params }: Props) {
  const id = Number(params.id); if (!Number.isInteger(id)) notFound();
  let media; try { media = await getMedia(id); } catch { notFound(); }
  const title = mediaTitle(media); const total = media.type === "ANIME" ? media.episodes : media.chapters; const description = await mediaDescription(media.description);
  return <div className="-mx-4 -mt-6 md:-mx-7"><section className="relative min-h-[540px] overflow-hidden border-b">{media.bannerImage ? <Image src={media.bannerImage} alt="" fill priority className="object-cover" sizes="100vw"/> : <div className="absolute inset-0 bg-gradient-to-br from-violet-900 to-slate-950"/>}<div className="absolute inset-0 bg-gradient-to-t from-background via-background/75 to-black/20"/><div className="relative mx-auto flex min-h-[540px] max-w-[1400px] items-end px-5 pb-10 pt-24 md:px-10"><div className="grid w-full gap-7 md:grid-cols-[200px_1fr]"><Image src={media.coverImage.extraLarge} alt={`Portada de ${title}`} width={300} height={450} priority className="hidden aspect-[2/3] w-full rounded-2xl object-cover shadow-2xl md:block"/><div className="self-end"><div className="mb-4 flex flex-wrap gap-2">{media.genres.slice(0,4).map((genre) => <Badge key={genre}>{genre}</Badge>)}</div><h1 className="max-w-4xl text-4xl font-black tracking-[-.04em] md:text-6xl">{title}</h1>{media.title.native && <p className="mt-2 text-lg text-muted-foreground">{media.title.native}</p>}<div className="mt-5 flex flex-wrap items-center gap-4 text-sm text-muted-foreground">{media.averageScore && <span className="flex items-center gap-1.5 font-semibold text-foreground"><Star className="size-4 fill-amber-400 text-amber-400"/>{(media.averageScore/10).toFixed(1)}</span>}<span className="flex items-center gap-1.5"><Tv2 className="size-4"/>{media.format ?? media.type}</span>{media.seasonYear && <span className="flex items-center gap-1.5"><CalendarDays className="size-4"/>{media.seasonYear}</span>}{total && <span>{total} {media.type === "ANIME" ? "episodios" : "capítulos"}</span>}</div><div className="mt-7 flex flex-wrap gap-3"><ListEditor mediaId={media.id} mediaType={media.type} title={title} coverUrl={media.coverImage.large} progressTotal={total}/><FavoriteButton mediaId={media.id} mediaType={media.type} title={title} coverUrl={media.coverImage.large}/>{media.trailer?.site === "youtube" && <a href={`https://youtube.com/watch?v=${media.trailer.id}`} target="_blank" rel="noreferrer" className="inline-flex h-12 items-center gap-2 rounded-xl border bg-background/50 px-6 text-sm font-semibold backdrop-blur transition hover:bg-accent"><Play className="size-4"/>Tráiler</a>}</div></div></div></div></section>
    <div className="mx-auto max-w-[1400px] space-y-12 px-5 py-10 md:px-10"><div className="grid gap-8 lg:grid-cols-[1fr_300px]"><section><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold">Sinopsis</h2>{description.translated && <span className="rounded-full bg-primary/10 px-2.5 py-1 text-[10px] font-semibold text-primary">Traducción automática</span>}</div><p className="mt-4 max-w-4xl whitespace-pre-line text-sm leading-7 text-muted-foreground md:text-base">{description.text}</p></section><aside className="rounded-2xl border bg-card p-5"><h2 className="font-bold">Información</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Estado</dt><dd>{media.status ?? "—"}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Formato</dt><dd>{media.format ?? "—"}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Estudio</dt><dd className="text-right">{media.studios?.nodes[0]?.name ?? "—"}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Popularidad</dt><dd>{media.popularity?.toLocaleString("es-ES") ?? "—"}</dd></div></dl>{media.externalLinks?.length ? <div className="mt-6 border-t pt-4"><p className="mb-3 text-xs font-bold uppercase tracking-wider text-muted-foreground">Dónde ver</p>{media.externalLinks.slice(0,5).map((link) => <a key={link.id} href={link.url} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-lg px-2 py-1.5 text-sm hover:bg-muted">{link.site}<ExternalLink className="size-3"/></a>)}</div> : null}</aside></div>
    {media.characters?.nodes.length ? <section><SectionHeading title="Personajes principales"/><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{media.characters.nodes.map((character) => <div key={character.id}><div className="relative aspect-[3/4] overflow-hidden rounded-2xl"><Image src={character.image.large} alt={character.name.full} fill sizes="150px" className="object-cover"/></div><p className="mt-2 truncate text-sm font-semibold">{character.name.full}</p></div>)}</div></section> : null}
    {media.recommendations?.nodes.length ? <section><SectionHeading title="También podría gustarte"/><MediaGrid media={media.recommendations.nodes.map((node) => node.mediaRecommendation).filter(Boolean)}/></section> : null}</div></div>;
}
