import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, BarChart3, Library, Sparkles } from "lucide-react";
import { AuthForm } from "@/components/auth-form";
import { Logo } from "@/components/logo";

export const metadata: Metadata = { title: "Acceso" };
export default function AccessPage() { return <main className="grid min-h-screen lg:grid-cols-2"><section className="relative hidden overflow-hidden bg-[#0b0815] p-12 text-white lg:flex lg:flex-col"><Image src="/koen-brand.jpg" alt="" fill priority sizes="50vw" className="object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-b from-black/45 via-[#0b0815]/60 to-[#0b0815]/90"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_10%,rgba(139,92,246,.10),transparent_35%),radial-gradient(circle_at_80%_80%,rgba(37,99,235,.10),transparent_35%)]"/><Logo className="relative"/><div className="relative my-auto max-w-xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-black/25 px-3 py-1.5 text-xs text-white/80 backdrop-blur-sm"><Sparkles className="size-3 text-violet-300"/>Anime · Manga · Novelas</span><h2 className="mt-6 text-5xl font-black leading-[1.08] tracking-[-.045em] drop-shadow-lg">Cada historia vive.<br/><span className="text-violet-300">Guárdala.</span></h2><p className="mt-5 max-w-md text-base leading-7 text-white/70 drop-shadow">Organiza lo que ves y lees, descubre nuevos favoritos y entiende tus hábitos como nunca antes.</p><div className="mt-10 grid grid-cols-3 gap-3">{[[Library,"Tu lista"],[BarChart3,"Estadísticas"],[Sparkles,"Descubrimiento"]].map(([Icon,label]) => { const I=Icon as typeof Library; return <div key={label as string} className="rounded-2xl border border-white/15 bg-black/25 p-4 backdrop-blur-sm"><I className="size-5 text-violet-300"/><p className="mt-3 text-xs font-semibold">{label as string}</p></div>; })}</div></div><p className="relative text-xs text-white/50">Koen · Hecho para quienes aman las historias</p></section><section className="flex items-center justify-center p-6 md:p-12"><div className="w-full max-w-md"><Link href="/inicio" className="mb-10 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/>Volver a explorar</Link><div className="mb-9 lg:hidden"><Logo/></div><AuthForm/></div></section></main>; }
