import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { BookOpen, CalendarDays, ExternalLink, UserRound } from "lucide-react";
import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { ListEditor } from "@/components/list-editor";
import { getNovelSeriesDetail } from "@/services/ranobedb";
import { translateToSpanish } from "@/services/translation";
import { novelPublicationStatus, novelTitle, ranobeImage } from "@/types/novel";
import { stripHtml } from "@/lib/utils";

interface Props { params: { id: string } }
async function novelDescription(novel: Awaited<ReturnType<typeof getNovelSeriesDetail>>) {
  const source = stripHtml(novel.book_description?.description || novel.description || novel.book_description?.description_ja) || "Sin sinopsis disponible.";
  return translateToSpanish(source);
}

export async function generateMetadata({ params }: Props): Promise<Metadata> { try { const novel = await getNovelSeriesDetail(Number(params.id)); const description = await novelDescription(novel); return { title: novelTitle(novel), description: description.text.slice(0,155) }; } catch { return { title: "Novela ligera" }; } }

export default async function NovelDetail({ params }: Props) {
  const id = Number(params.id); if (!Number.isInteger(id)) notFound();
  let novel; try { novel = await getNovelSeriesDetail(id); } catch { notFound(); }
  const title = novelTitle(novel); const cover = ranobeImage(novel.books[0]?.image?.filename); const authors = novel.staff.filter((staff) => staff.role_type === "author"); const artists = novel.staff.filter((staff) => staff.role_type === "artist"); const year = String(novel.start_date).slice(0,4); const description = await novelDescription(novel);
  return <div className="mx-auto max-w-[1400px] space-y-12"><section className="relative overflow-hidden rounded-3xl border bg-card p-6 shadow-card md:p-10">{cover && <Image src={cover} alt="" fill priority className="scale-110 object-cover opacity-15 blur-2xl" sizes="100vw"/>}<div className="absolute inset-0 bg-gradient-to-r from-card via-card/95 to-card/70"/><div className="relative grid gap-8 md:grid-cols-[220px_1fr]">{cover ? <Image src={cover} alt={`Portada de ${title}`} width={300} height={450} priority className="aspect-[2/3] w-full rounded-2xl object-cover shadow-2xl"/> : <div className="grid aspect-[2/3] place-items-center rounded-2xl bg-muted"><BookOpen className="size-14 text-muted-foreground"/></div>}<div className="self-center"><div className="mb-4 flex flex-wrap gap-2">{novel.tags.filter((tag) => tag.ttype === "genre").map((tag) => <Badge key={tag.id}>{tag.name}</Badge>)}</div><h1 className="text-4xl font-black tracking-[-.04em] md:text-5xl">{title}</h1>{novel.title_orig && <p className="mt-2 text-muted-foreground">{novel.title_orig}</p>}<div className="mt-5 flex flex-wrap gap-4 text-sm text-muted-foreground"><span className="flex items-center gap-1.5"><BookOpen className="size-4"/>{novel.books.length} volúmenes</span>{novel.start_date && <span className="flex items-center gap-1.5"><CalendarDays className="size-4"/>{year}</span>}<span>Estado de publicación: {novelPublicationStatus(novel.publication_status)}</span></div><div className="mt-7 flex flex-wrap gap-3"><ListEditor mediaId={novel.id} mediaType="NOVEL" title={title} coverUrl={cover} progressTotal={novel.books.length}/>{novel.web_novel && <a href={novel.web_novel} target="_blank" rel="noreferrer" className="inline-flex h-12 items-center gap-2 rounded-xl border px-6 text-sm font-semibold hover:bg-accent">Sitio oficial<ExternalLink className="size-4"/></a>}</div></div></div></section>
    <div className="grid gap-8 lg:grid-cols-[1fr_300px]"><section><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold">Sinopsis</h2>{description.translated && <span className="rounded-full bg-primary/10 px-2.5 py-1 text-[10px] font-semibold text-primary">Traducción automática</span>}</div><p className="mt-4 whitespace-pre-line text-sm leading-7 text-muted-foreground md:text-base">{description.text}</p></section><aside className="rounded-2xl border bg-card p-5"><h2 className="font-bold">Créditos</h2><div className="mt-4 space-y-4 text-sm">{authors.length > 0 && <div><p className="text-xs text-muted-foreground">Autoría</p>{authors.map((author) => <p key={author.staff_id} className="mt-1 flex items-center gap-2"><UserRound className="size-3"/>{author.romaji || author.name}</p>)}</div>}{artists.length > 0 && <div><p className="text-xs text-muted-foreground">Ilustración</p>{artists.map((artist) => <p key={artist.staff_id} className="mt-1">{artist.romaji || artist.name}</p>)}</div>}<div><p className="text-xs text-muted-foreground">Editoriales</p><p className="mt-1">{novel.publishers.filter((publisher) => publisher.publisher_type === "publisher").map((publisher) => publisher.romaji || publisher.name).join(", ") || "—"}</p></div></div></aside></div>
    <section><h2 className="mb-5 text-2xl font-bold">Volúmenes</h2>{novel.books.length > 0 ? <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-5 lg:grid-cols-7">{novel.books.map((book,index) => { const image = ranobeImage(book.image?.filename); return <Link key={book.id} href={`/novelas/${novel.id}/volumenes/${book.id}`} className="group rounded-xl focus:outline-none focus-visible:ring-2 focus-visible:ring-primary">{image ? <div className="relative aspect-[2/3] overflow-hidden rounded-xl bg-muted shadow-card"><Image src={image} alt={`Portada de ${novelTitle(book)}`} fill sizes="140px" className="object-cover transition duration-300 group-hover:scale-105"/></div> : <div className="grid aspect-[2/3] place-items-center rounded-xl bg-muted"><BookOpen/></div>}<p className="mt-2 line-clamp-2 text-xs font-semibold transition group-hover:text-primary">{novelTitle(book)}</p><p className="mt-1 text-[11px] text-muted-foreground">Volumen {book.sort_order || index+1}</p></Link>; })}</div> : <p className="rounded-2xl border bg-card p-6 text-sm text-muted-foreground">RanobeDB todavía no tiene volúmenes asociados a esta serie.</p>}</section><p className="text-center text-xs text-muted-foreground">Datos de RanobeDB. Los enlaces externos se muestran únicamente cuando la fuente oficial los proporciona.</p></div>;
}
