import { NextResponse } from "next/server";
import { z } from "zod";
import { isSupabaseConfigured } from "@/lib/env";
import { createClient } from "@/lib/supabase/server";

const ENDPOINT = "https://graphql.anilist.co";
const bodySchema = z.discriminatedUnion("source", [z.object({source:z.literal("anilist"),username:z.string().trim().min(2).max(50)}),z.object({source:z.literal("mal"),xml:z.string().min(20).max(4_000_000)})]);
interface ImportedEntry { media_id:number;media_type:"ANIME"|"MANGA";title:string;cover_url:string|null;status:string;progress:number;progress_total:number|null;score:number|null;notes:string|null }
interface AniEntry { progress:number;score:number;notes:string|null;status:string;media:{id:number;idMal:number|null;type:"ANIME"|"MANGA";episodes:number|null;chapters:number|null;title:{romaji:string|null;english:string|null;native:string|null};coverImage:{large:string}} }
const STATUS:Record<string,string>={CURRENT:"watching",COMPLETED:"completed",PLANNING:"planning",PAUSED:"paused",DROPPED:"dropped",REPEATING:"repeating",Watching:"watching",Reading:"reading",Completed:"completed","Plan to Watch":"planning","Plan to Read":"planning","On-Hold":"paused",Dropped:"dropped"};
const title=(media:AniEntry["media"])=>media.title.romaji||media.title.english||media.title.native||"Título desconocido";
async function anilist<T>(query:string,variables:Record<string,unknown>):Promise<T>{const response=await fetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({query,variables}),cache:"no-store"});if(!response.ok)throw new Error();const payload=await response.json() as{data?:T};if(!payload.data)throw new Error();return payload.data;}
async function fromAniList(username:string){const query=`query($name:String,$type:MediaType){MediaListCollection(userName:$name,type:$type){lists{entries{status progress score notes media{id idMal type episodes chapters title{romaji english native}coverImage{large}}}}}}`;const results=await Promise.all([anilist<{MediaListCollection:{lists:Array<{entries:AniEntry[]}>}}>(query,{name:username,type:"ANIME"}),anilist<{MediaListCollection:{lists:Array<{entries:AniEntry[]}>}}>(query,{name:username,type:"MANGA"})]);return results.flatMap(result=>result.MediaListCollection.lists.flatMap(list=>list.entries)).map((entry):ImportedEntry=>({media_id:entry.media.id,media_type:entry.media.type,title:title(entry.media),cover_url:entry.media.coverImage.large,status:entry.media.type==="MANGA"&&entry.status==="CURRENT"?"reading":STATUS[entry.status]??"planning",progress:entry.progress??0,progress_total:entry.media.type==="ANIME"?entry.media.episodes:entry.media.chapters,score:entry.score||null,notes:entry.notes||null}));}
const tag=(block:string,name:string)=>{const match=block.match(new RegExp(`<${name}>(?:<!\\[CDATA\\[)?([\\s\\S]*?)(?:\\]\\]>)?<\\/${name}>`,`i`));return match?.[1]?.trim().replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">")??"";};
async function fromMal(xml:string){const isManga=/<manga>/i.test(xml);const blocks=[...xml.matchAll(new RegExp(isManga?"<manga>([\\s\\S]*?)<\\/manga>":"<anime>([\\s\\S]*?)<\\/anime>","gi"))].map(match=>match[1]).slice(0,5000);const raw=blocks.map(block=>({id:Number(tag(block,isManga?"manga_mangadb_id":"series_animedb_id")),status:tag(block,"my_status"),progress:Number(tag(block,isManga?"my_read_chapters":"my_watched_episodes"))||0,score:Number(tag(block,"my_score"))||null})).filter(item=>item.id>0);const mediaMap=new Map<number,AniEntry["media"]>();for(let offset=0;offset<raw.length;offset+=50){const ids=raw.slice(offset,offset+50).map(item=>item.id);const query=`query($ids:[Int],$type:MediaType){Page(perPage:50){media(idMal_in:$ids,type:$type){id idMal type episodes chapters title{romaji english native}coverImage{large}}}}`;const data=await anilist<{Page:{media:AniEntry["media"][]}}>(query,{ids,type:isManga?"MANGA":"ANIME"});data.Page.media.forEach(media=>{if(media.idMal)mediaMap.set(media.idMal,media)});}return raw.flatMap((item):ImportedEntry[]=>{const media=mediaMap.get(item.id);if(!media)return[];return[{media_id:media.id,media_type:media.type,title:title(media),cover_url:media.coverImage.large,status:media.type==="MANGA"&&item.status==="Reading"?"reading":STATUS[item.status]??"planning",progress:item.progress,progress_total:media.type==="ANIME"?media.episodes:media.chapters,score:item.score,notes:null}]});}
export async function POST(request:Request){if(!isSupabaseConfigured)return NextResponse.json({error:"Supabase no está configurado."},{status:503});const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Acceso requerido."},{status:401});const parsed=bodySchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Los datos de importación no son válidos."},{status:400});try{const entries=parsed.data.source==="anilist"?await fromAniList(parsed.data.username):await fromMal(parsed.data.xml);for(let offset=0;offset<entries.length;offset+=100){const rows=entries.slice(offset,offset+100).map(entry=>({...entry,user_id:user.id}));const{error}=await supabase.from("user_lists").upsert(rows,{onConflict:"user_id,media_id,media_type"});if(error)throw error;}await supabase.from("activity").insert({user_id:user.id,kind:"import",metadata:{source:parsed.data.source,count:entries.length}});return NextResponse.json({count:entries.length});}catch{return NextResponse.json({error:"No pudimos completar la importación. Revisa el usuario o el archivo."},{status:502});}}
